import nodemailer from 'nodemailer';

const smtpHost = process.env.SMTP_HOST || '';
const smtpPort = parseInt(process.env.SMTP_PORT || '587');
const smtpUser = process.env.SMTP_USER || '';
const smtpPass = process.env.SMTP_PASS || '';
const adminEmail = process.env.ADMIN_NOTIFICATION_EMAIL || 'admin@kiwiclicks.com';

const isMailConfigured = !!(smtpHost && smtpUser && smtpPass);

let transporter: nodemailer.Transporter | null = null;

if (isMailConfigured) {
  transporter = nodemailer.createTransport({
    host: smtpHost,
    port: smtpPort,
    secure: smtpPort === 465,
    auth: {
      user: smtpUser,
      pass: smtpPass,
    },
  });
}

export const sendLeadNotification = async (lead: {
  name: string;
  email: string;
  phone?: string | null;
  service: string;
  budget?: string | null;
  message: string;
}) => {
  const subject = `🚨 New Contact Lead: ${lead.name} - ${lead.service}`;
  const html = `
    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; padding: 20px; border-radius: 8px;">
      <h2 style="color: #1B4D3E; border-bottom: 2px solid #FF8A3D; padding-bottom: 10px;">New KiwiClicks Contact Form Submission</h2>
      <p style="font-size: 16px; color: #333;">A new lead has been submitted on the website. Here are the details:</p>
      
      <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
        <tr>
          <td style="padding: 8px; border-bottom: 1px solid #eeeeee; font-weight: bold; width: 120px;">Name:</td>
          <td style="padding: 8px; border-bottom: 1px solid #eeeeee;">${lead.name}</td>
        </tr>
        <tr>
          <td style="padding: 8px; border-bottom: 1px solid #eeeeee; font-weight: bold;">Email:</td>
          <td style="padding: 8px; border-bottom: 1px solid #eeeeee;"><a href="mailto:${lead.email}">${lead.email}</a></td>
        </tr>
        <tr>
          <td style="padding: 8px; border-bottom: 1px solid #eeeeee; font-weight: bold;">Phone:</td>
          <td style="padding: 8px; border-bottom: 1px solid #eeeeee;">${lead.phone || 'N/A'}</td>
        </tr>
        <tr>
          <td style="padding: 8px; border-bottom: 1px solid #eeeeee; font-weight: bold;">Service:</td>
          <td style="padding: 8px; border-bottom: 1px solid #eeeeee; font-weight: bold; color: #4A9C3A;">${lead.service}</td>
        </tr>
        <tr>
          <td style="padding: 8px; border-bottom: 1px solid #eeeeee; font-weight: bold;">Budget Scope:</td>
          <td style="padding: 8px; border-bottom: 1px solid #eeeeee;">${lead.budget || 'N/A'}</td>
        </tr>
      </table>

      <div style="margin-top: 20px; background-color: #f9f9f9; padding: 15px; border-radius: 5px; border-left: 4px solid #FF8A3D;">
        <p style="font-weight: bold; margin-top: 0; margin-bottom: 5px;">Message:</p>
        <p style="margin: 0; color: #555; white-space: pre-wrap;">${lead.message}</p>
      </div>

      <p style="margin-top: 25px; font-size: 12px; color: #999; text-align: center;">
        This email was automatically generated by the KiwiClicks CMS Backend.
      </p>
    </div>
  `;

  if (transporter) {
    try {
      await transporter.sendMail({
        from: `"KiwiClicks Leads" <${smtpUser}>`,
        to: adminEmail,
        subject,
        html,
      });
      console.log(`Email notification sent to ${adminEmail} successfully.`);
    } catch (error) {
      console.error('Failed to send SMTP email notification:', error);
    }
  } else {
    // Development fallback: Log the email template to stdout
    console.log(`\n================= MOCK EMAIL NOTIFICATION =================`);
    console.log(`TO: ${adminEmail}`);
    console.log(`SUBJECT: ${subject}`);
    console.log(`CONTENT:`);
    console.log(`- Name: ${lead.name}`);
    console.log(`- Email: ${lead.email}`);
    console.log(`- Phone: ${lead.phone || 'N/A'}`);
    console.log(`- Service: ${lead.service}`);
    console.log(`- Budget: ${lead.budget || 'N/A'}`);
    console.log(`- Message: ${lead.message}`);
    console.log(`===========================================================\n`);
  }
};
export default sendLeadNotification;
